### ISSUE TITLE
Failed opening 'Wallee/Payment/Model/PaymentMethod1.php' for inclusion

### ISSUE THREAD

**Issue by steffen-wirth** [wallee-payment/magento#1]
Hi,

i installed the last commit in our test environment but the Payment Method is not shown in checkout and we see this error in the system.log  "ERR (3): Warning: include(Wallee/Payment/Model/PaymentMethod1.php): failed to open stream: No such file or directory  in .." and actually there is no such file only a template File Template.php.tpl. Can't find any installation instruction for this. 

best
Steffen

UPDATE:
I've seen that you dynamically create the payment method classes but i dont know excactly how. we restrict access on our testsystem by http auth - can that be the problem?

**Comment by schurter-wallee** [comment]
Hi Steffen,

the files containing the payment method classes are automatically generated and stored in var/wallee/. For this to happen, the web server needs to be able to write to this directory. Can you please check the file permissions and try again?

**Comment by steffen-wirth** [comment]
ok, i see.... file is created - but payment method still not showing up in checkout
And now saving the configuration in backend shows a message of limited webhooks
The limit of 'Webhook Listener Limit' is reached. The current limit is set to '30' - any idea on this one? thx!!!

**Comment by thomashunziker** [comment]
Most likely you need to remove some of the web hooks which the module automatically setups when it is installed. There is a limit to not have more than 30 web hook listeners setup within a particular space.

**Comment by nickweisser** [comment]
OK, but which ones should we delete?
![screen shot 2018-02-12 at 19 12 16](https://user-images.githubusercontent.com/58966/36112073-b43f7916-1028-11e8-8fef-e2afeb1ea216.png)

**Comment by thomashunziker** [comment]
I suspect that the 'Inactive' ones can be removed.

**Comment by nickweisser** [comment]
Thanks, did that already and it seems to be working, although it's still acting weird sometimes. Will keep you posted ...
