### ISSUE TITLE
Broken checkout when not configured

### ISSUE THREAD

**Issue by tschifftner** [wallee-payment/magento#3]
Currently the checkout breaks because this.informationUrl is set to null. Therefore a redirect is triggered to the cart. Also there is no option to enable/disable the payment method?!

```
	fetchInformation: function(callback) {
		if(!this.informationUrl) {
			return;
		}
		// ...
	},
	
```

**Comment by schurter-wallee** [comment]
Hi Tobias

Thanks for reporting this issue. In the version 1.0.50 that we just released it is fixed.

Payment methods can be disabled, you can either do this in wallee or in Magento by switching the configuration to website scope.

Regards, Simon
