### ISSUE TITLE
Call to getMethodInstance() on Mage_Sales_Model_Order_Payment of a Wallee order

### ISSUE THREAD

**Issue by GautierArc** [wallee-payment/magento#4]
In Magento, for example with the Magento Paypal payment method paypal_standard, when calling call `$order->getPayment()->getMethodInstance()` it returns the object `Mage_Paypal_Model_Standard`. When doing the same with a Wallee payment method, it will just trow an error `The requested Payment Method is not available.` coming from `app/code/core/Mage/Payment/Model/Info.php:82` because `$this->hasMethodInstance()` return false where it should return true.

**Comment by theodorspringwallee** [comment]
Dear [GautierDig](https://github.com/GautierDig)

Thank you for your input.

Can you tell us, under which circumstances you received the described behavior with our plugin?
That we can reproduce it in a use case.

Or did you receive the error during some own programming within the Magento shop?

Many thanks for your answers.

Best regards

**Comment by GautierArc** [comment]
Sorry, the issue was on our side. I close the issue.
